new steps added

diff --git a/.github/workflows/setup-kind-and-argocd.yaml b/.github/workflows/setup-kind-and-argocd.yaml
--- a/.github/workflows/setup-kind-and-argocd.yaml
+++ b/.github/workflows/setup-kind-and-argocd.yaml
@@ -15,7 +15,7 @@ jobs:
                 | 
                 if ! command -v docker &> /dev/null; then
                     echo "docker not installed"
-                    echo "installing docker"
+                    echo "installing docker ..................."
                     sudo apt-get update
                     sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
                     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
@@ -35,7 +35,7 @@ jobs:
                 | 
                 if ! command -v kind &> /dev/null; then
                     echo "kind not installed"
-                    echo "installing kind"
+                    echo "installing kind ......................" 
                     wget https://github.com/kubernetes-sigs/kind/releases/download/v0.18.0/kind-linux-amd64
                     sudo mv kind-linux-amd64 /usr/local/bin/kind
                     sudo chmod +x /usr/local/bin/kind
@@ -49,7 +49,7 @@ jobs:
                 | 
                 if ! command -v kubectl &> /dev/null; then
                     echo "kubectl not installed"
-                    echo "installing kubectl"
+                    echo "installing kubectl ....................."
                     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                     sudo mv kubectl /usr/local/bin
                     sudo chmod +x /usr/local/bin/kubectl
@@ -58,5 +58,29 @@ jobs:
                 else
                     echo "kubectl is already installed"
                 fi
+
+            - name: check and create app cluster
+              run:
+                | 
+                if ! kind get clusters | grep -q "apps-cluster"; then 
+                    echo "app-cluster not found"
+                    echo "creating app-cluster ...................."
+                    kind create cluster --name apps-cluster --config clusters/apps-cluster.yaml
+                else
+                    echo "apps-cluster already exists."
+                fi
+            
+            - name: check and create datalake cluster
+              run:
+                |
+                if ! kind get clusters | grep -q "datalake-cluster": then
+                     echo "datalake-cluster not found"
+                     echo "creating datalake cluster ..............."
+                     kind create cluster -- name datalake-cluster --config clusters/datalake-cluster.yaml
+                else
+                    echo "datalake cluster already exists."
+                fi
+
+
             
   
