new steps added for argocd installation

diff --git a/.github/workflows/setup-kind-and-argocd.yaml b/.github/workflows/setup-kind-and-argocd.yaml
--- a/.github/workflows/setup-kind-and-argocd.yaml
+++ b/.github/workflows/setup-kind-and-argocd.yaml
@@ -84,7 +84,50 @@ jobs:
                 else
                     echo "datalake cluster already exists."
                 fi
-
+            - name: set kubectl context to apps-cluster
+              run:
+                  |
+                  kubectl config use-context kind-apps-cluster
+            - name: Install Argo CD CLI
+              run: |
+                    if ! command -v argocd &> /dev/null; then
+                      echo "Installing Argo CD CLI..."
+                      curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+                      chmod +x argocd
+                      sudo mv argocd /usr/local/bin/
+                    else
+                      echo "Argo CD CLI already installed."
+                    fi
+            
+            - name: Check and Install Argo CD
+              run: 
+                 |
+                  echo "Checking if Argo CD is already installed..."
+                  if ! kubectl get ns argocd &> /dev/null; then
+                    echo "argocd namespace not found; installing and creating namespace"
+                    kubectl create namespace argocd
+                    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
+                  else
+                    echo "Argo CD is already installed. Skipping installation."
+                  fi
+            
+            - name: Wait for Argo CD server to be ready
+              if: success()
+              run: |
+                    kubectl -n argocd rollout status deploy/argocd-server --timeout=180s
+            
+            - name: Port-forward Argo CD UI (for local access)
+              run: |
+                      nohup kubectl port-forward svc/argocd-server -n argocd 8080:443 &
+            
+                      - name: Show Argo CD login instructions (no password printed)
+                      run: |
+                        echo "🔐 Argo CD is now installed."
+                        echo "🌐 Open: https://localhost:8080"
+                        echo "👤 Username: admin"
+                        echo "🔑 To get the password, run this:"
+                        echo 'kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d && echo'
+              
 
             
   
